### ISSUE TITLE
wip: user onboarding experience

### ISSUE THREAD

**Issue by Shurtu-gal** [Monday-Morning/project-tahiti#442]
**Tasks:**

- [x] Add loader during onboarding
- [x] Check if Zimbra mail is already registered.
- [x] Custom error handling.
