### ISSUE TITLE
wip: admin-panel

### ISSUE THREAD

**Issue by Shurtu-gal** [Monday-Morning/project-tahiti#446]
**Tasks:**

- [ ] Add Contributions Mutation
- [ ] Add UserForm Mutation
- [ ] Add Media UI + Mutation
- [ ] Add Docs Support with permission handling

**Additional Context**
Related to admin panel

**Comment by rutajdash** [comment]
@Shurtu-gal @120EE0692 please make an umbrella issue [(like this)](https://github.com/flutter/flutter/issues/91605) for this and track all related issues in it. Either convert this into it or close this and make a new one.

Also, let's make this a level 1 priority right now.
